# A glimpse into NumPy

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Mathematical Operations


The NumPy array, provides a different set of functionality that is really useful -- especially for numeric computations.

Lets compare the syntax for mathematical operations on a list and an array.

Say we want to add 1 to every element in a sequence. 

First we do it on a list

In [2]:
x = [11, 24, 36, 54]
x

[11, 24, 36, 54]

In [3]:
x+1

TypeError: can only concatenate list (not "int") to list

We get an error as we can't add a list and an integer data types.

In [4]:
[x + 1 for x in x]

[12, 25, 37, 55]

Now it works, but it is not very intuitive.

However, if we convert `x` to a NumPy `array`, then we can add 1 to it.


In [5]:
x = np.array(x)
x+1

array([12, 25, 37, 55])

Thus when we perform a mathematical operation on our array, the operation is performed every element. This is referred to as `broadcasting`.

## Operations on two Arrays

NumPy also performs element-by-element operations when operating on two arrays.

Let's create one more array `y`:

In [6]:
y = np.array([5, 8, 6, 3])

They both have 4 elements.  If we add `x` and `y`:

In [7]:
x + y

array([16, 32, 42, 57])

Multiply:

In [8]:
x*y

array([ 55, 192, 216, 162])

Exponentiate:

In [9]:
x**y

array([      161051, 110075314176,   2176782336,       157464])

## Element selection from an Array

We can index arrays just like lists:

In [10]:
x[0]

11

We can slice:

In [11]:
x[:2]

array([11, 24])

In [12]:
x[-2:]

array([36, 54])

We can also add the first 2 to the last 2:

In [13]:
x[:2] + x[-2:]

array([47, 78])

## Multi-dimensional Arrays

Multi-dimensional Arrays have two or more dimensions.  Let's reshape the `x` array to get a two rows and two columns array.

In [14]:
x.shape

(4,)

the shape can be changed dynamically:

In [15]:
x.shape = (2, 2)
x

array([[11, 24],
       [36, 54]])

It is your responsibility that the initial shape and the targeted shape 
are commensurate:

In [17]:
z = np.array([1,2,3,5,7])
z.shape = (2,3)

ValueError: cannot reshape array of size 5 into shape (2,3)

If we multiply x by itself:

In [18]:
x*x

array([[ 121,  576],
       [1296, 2916]])

### Multidimensional arrays and indexing

In [53]:
# A 3x3 matrix
A = np.array([[   11,     12,     13    ],  # Row 0
              [   21,     22,     23    ],  # Row 1
              [   31,     32,     33    ]]) # Row 2
#                 Col 0   Col 1   Col 2
                 
    

In [54]:
# Get row 1:
A[1,:]

array([21, 22, 23])

In [55]:
# Get col 2:
A[:,2]

array([13, 23, 33])

In [56]:
# Transposition
A.T

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

### Linear Algebra, products of arrays
`numpy` defines a number of product operations besides the `*` product:


In [57]:
# dot product (aka scalar or inner product)
a = np.array([1,2])
b = np.array([-2, 1])

a.dot(b)

0

In [58]:
# Outer product outer_ij = a_i * b_j
np.outer(a,b)

array([[-2,  1],
       [-4,  2]])

In [59]:
# dot product between a 2D array ("Matrix") and a 1D vector
B = np.array([[0,1],
              [1,0]])

print(B)

[[0 1]
 [1 0]]


In [60]:
B.dot(a)

array([2, 1])

In [64]:
# Eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(B)

In [65]:
eigenvalues

array([ 1., -1.])

In [66]:
eigenvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

**Note**: The vectors that solve the EVE are the **columns** of the eigenvector array.

In [67]:
B.dot(eigenvectors[:,1]) - eigenvalues[1]*eigenvectors[:,1]

array([0., 0.])

### Array methods

#### Summation

In [73]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [68]:

# Sum over all elements.
A.sum()

198

In [71]:
# Sum values in columns.
A.sum(axis=0)

array([63, 66, 69])

In [74]:
# Sum in rows
A.sum(axis=1)

array([36, 66, 96])

#### Find the maximum/minimum values

In [78]:
A.max(), A.min()

(33, 11)

In [79]:
A.max(axis=0), A.min(axis=0)

(array([31, 32, 33]), array([11, 12, 13]))

In [80]:
A.max(axis=1), A.min(axis=1)

(array([13, 23, 33]), array([11, 21, 31]))

In [82]:
#### Flattened array

In [83]:
A.flatten()

array([11, 12, 13, 21, 22, 23, 31, 32, 33])

#### Indices of max/min, corresponds to index in the flattened array.

In [84]:
A.argmax()

8

#### Boolean masking

In [88]:
A<22

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [89]:
A[A<22]

array([11, 12, 13, 21])