# Solutions numpy (day 3)

In [1]:
import numpy as np

In [101]:
magic = np.array(
    [
        [ 16,  3,  2, 13],
        [  5, 10, 11,  8],
        [  9,  6,  7, 12],
        [  4, 15, 14,  1]
    ]
)

In [3]:
magic

array([[16,  3,  2, 13],
       [ 5, 10, 11,  8],
       [ 9,  6,  7, 12],
       [ 4, 15, 14,  1]])

In [5]:
# 2
magic.sum(axis=0)

array([34, 34, 34, 34])

In [6]:
# 3
magic.sum(axis=1)

array([34, 34, 34, 34])

In [8]:
# 4a
magic.diagonal().sum()

34

In [9]:
# 4b
magic[::-1].diagonal().sum()

34

In [10]:
# 5
(
magic[:2,:2].sum(),
magic[2:,:2].sum(),
magic[:2,2:].sum(),
magic[:2,2:].sum(),
)

(34, 34, 34, 34)

In [11]:
# 6
magic.max(axis=0).sum()

58

In [12]:
# 6
magic.max(axis=1).sum()

54

In [13]:
# 7
(
    magic.mean(),
    magic.mean(axis=0),
    magic.mean(axis=1)
)

(8.5, array([8.5, 8.5, 8.5, 8.5]), array([8.5, 8.5, 8.5, 8.5]))

In [16]:
# 8
(
    np.median(magic,),
    np.median(magic,axis=0),
    np.median(magic,axis=1)
)

(8.5, array([ 7.,  8.,  9., 10.]), array([8., 9., 8., 9.]))

In [30]:
magic.flatten().cumsum()/magic.sum()

array([0.11764706, 0.13970588, 0.15441176, 0.25      , 0.28676471,
       0.36029412, 0.44117647, 0.5       , 0.56617647, 0.61029412,
       0.66176471, 0.75      , 0.77941176, 0.88970588, 0.99264706,
       1.        ])

In [60]:
# 10 A
def quantilles(a, axis=None):
    """ Function to return the 25%, 50%, and 75% quantilles"""
        
    a = a.flatten()
    a.sort()
    # Sum
    rel_cum_sum = a.cumsum()/a.sum()
    
    print(rel_cum_sum)
    
    smaller_25 = rel_cum_sum < 0.25
    larger_25 = rel_cum_sum > 0.25
    
    print(a[smaller_25])
    print(a[larger_25])
    
    def midpoint(a,b):
        return 0.5*(a+b)
    
    return midpoint(a[smaller_25][-1], a[larger_25][0])
    
    
    

In [61]:
quantilles(magic)

[0.00735294 0.02205882 0.04411765 0.07352941 0.11029412 0.15441176
 0.20588235 0.26470588 0.33088235 0.40441176 0.48529412 0.57352941
 0.66911765 0.77205882 0.88235294 1.        ]
[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15 16]


7.5

In [45]:
quantilles(magic, axis=0)

(array([8.5, 8.5, 8.5, 8.5]),
 array([17., 17., 17., 17.]),
 array([25.5, 25.5, 25.5, 25.5]))

In [46]:
quantilles(magic, axis=1)

(array([8.5, 8.5, 8.5, 8.5]),
 array([17., 17., 17., 17.]),
 array([25.5, 25.5, 25.5, 25.5]))

In [48]:
# 10 B
np.quantile(magic, q=0.25)

4.75

In [49]:
# 10 B
np.quantile(magic, q=0.5)

8.5

In [64]:
# 11 A
np.zeros(shape=(100, 100))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [65]:
np.ones(shape=(20, 30, 40))

array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       ...,

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1.

In [67]:
# 11 C
np.eye(10, 10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [69]:
# 11 D
D = np.random.random((20, 20))

In [70]:
# 11 E
E = np.zeros_like(D)

In [71]:
# 11 F
F = np.ones_like(D)

In [72]:
# 11 G
G = np.arange(10); G

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
H = np.arange(-5,5); H

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [78]:
I = np.arange(-10, 10, 2); I

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [85]:
magic

array([[16,  3,  2, 13],
       [ 5, 10, 11,  8],
       [ 9,  6,  7, 12],
       [ 4, 15, 14,  1]])

#### The inverse
A matrix only has an inverse, if it's determinant is non-zero

In [103]:
np.linalg.det(magic)

2.4317390206737117e-13

well, almost zero. Hence, the following will not produce sensible results.

In [104]:
J = np.linalg.inv(1.*magic); J

array([[ 5.59270542e+14,  1.67781163e+15, -1.67781163e+15,
        -5.59270542e+14],
       [-1.67781163e+15, -5.03343488e+15,  5.03343488e+15,
         1.67781163e+15],
       [ 1.67781163e+15,  5.03343488e+15, -5.03343488e+15,
        -1.67781163e+15],
       [-5.59270542e+14, -1.67781163e+15,  1.67781163e+15,
         5.59270542e+14]])

In [91]:
K = magic.dot(J); K


array([[ 2.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  4.],
       [ 0., -8.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [93]:
L = J*magic; L

array([[ 8.94832867e+15,  5.03343488e+15, -3.35562325e+15,
        -7.27051705e+15],
       [-8.38905813e+15, -5.03343488e+16,  5.53677837e+16,
         1.34224930e+16],
       [ 1.51003046e+16,  3.02006093e+16, -3.52340441e+16,
        -2.01337395e+16],
       [-2.23708217e+15, -2.51671744e+16,  2.34893628e+16,
         5.59270542e+14]])

In [98]:
M = np.outer(magic,J); M

array([[ 8.94832867e+15,  2.68449860e+16, -2.68449860e+16,
        -8.94832867e+15, -2.68449860e+16, -8.05349580e+16,
         8.05349580e+16,  2.68449860e+16,  2.68449860e+16,
         8.05349580e+16, -8.05349580e+16, -2.68449860e+16,
        -8.94832867e+15, -2.68449860e+16,  2.68449860e+16,
         8.94832867e+15],
       [ 1.67781163e+15,  5.03343488e+15, -5.03343488e+15,
        -1.67781163e+15, -5.03343488e+15, -1.51003046e+16,
         1.51003046e+16,  5.03343488e+15,  5.03343488e+15,
         1.51003046e+16, -1.51003046e+16, -5.03343488e+15,
        -1.67781163e+15, -5.03343488e+15,  5.03343488e+15,
         1.67781163e+15],
       [ 1.11854108e+15,  3.35562325e+15, -3.35562325e+15,
        -1.11854108e+15, -3.35562325e+15, -1.00668698e+16,
         1.00668698e+16,  3.35562325e+15,  3.35562325e+15,
         1.00668698e+16, -1.00668698e+16, -3.35562325e+15,
        -1.11854108e+15, -3.35562325e+15,  3.35562325e+15,
         1.11854108e+15],
       [ 7.27051705e+15,  2.18115511e